from pydantic import BaseModel, Field, create_model
from typing import Literal


class InputSchema(BaseModel):
    # explanation: str = Field(..., title="The explanation or reasoning behind the input (i.e., ingredients/materials, tools). Carefully consider both the subtitles, the visuals, and the context of the tutorial.")
    # description: str = Field(..., title="A detailed description of the input (i.e., ingredients/materials, tools) that can be inferred from the subtitles or the visuals.")
    title: str = Field(..., title="A concise title of the input that captures its important specifications.")

class InputWithSourceSchema(InputSchema):
    source_step: str = Field(..., title="The title of the step that generates this input. This should be a reference to the step title. If the input is not generated by any step, use 'None'.")
    source_step_index: int = Field(..., title="The index of the step that generates this input. This should be a reference to the step index. If the input is not generated by any step, use -1.")


class OutputSchema(BaseModel):
    # explanation: str = Field(..., title="The explanation or reasoning behind the output (i.e., result, effect). Carefully consider both the subtitles, the visuals, and the context of the tutorial.")
    # description: str = Field(..., title="A detailed description of the output that can be inferred from the subtitles or the visuals.")
    title: str = Field(..., title="A concise title of the output that captures its important specifications.")

class OutputWithSourceSchema(OutputSchema):
    step: str = Field(..., title="The title of the step that generates this output. This should be a reference to the step title. If the output is not generated by any step, use 'None'.")
    step_index: int = Field(..., title="The index of the step that generates this output. This should be a reference to the step index. If the output is not generated by any step, use -1.")

class StepSchema(BaseModel):
    # explanation: str = Field(..., title="The explanation or reasoning behind the step. Carefully consider both the subtitles, the visuals, and the context of the tutorial.")
    detailed_description: str = Field(..., title="A detailed description of the step that can be inferred from the subtitles or the visuals. Make sure to include all the necessary details such as the tools, materials, ingredients, or the method.")
    title: str = Field(..., title="A concise title of the step that captures its important specifications. Focus on the actions and methods.")
    # action_description: str = Field(..., title="The action that the step is performing. This should be a veb phrase that describes the action and does not include any nouns.")

class StepWithInputSchema(StepSchema):
    inputs: list[InputSchema] = Field(..., title="A comprehensive list of discrete inputs for the step that can be inferred from the tutorial. Specify one input at a time.")
    index: int = Field(..., title="The index of the step in the tutorial.")

class ProceduralElementsSchema(BaseModel):
    steps: list[StepWithInputSchema] = Field(..., title="A comprehensive list of steps included in the tutorial.")
    outputs: list[OutputSchema] = Field(..., title="A comprehensive list of discrete final outcomes of the tutorial that can be inferred from the subtitles or the visuals. Specify one output at a time.")

class CleanStepDescription(BaseModel):
    description: str = Field(..., title="Masked description of the step.")


class TaxonomyAssignmentSchema(BaseModel):
    taxonomy_index: int = Field(..., title="The index of the taxonomy entry.")
    taxonomy_entry: str = Field(..., title="The title of the taxonomy entry.")
    is_included: bool = Field(..., title="Whether the tutorial contains the taxonomy entry.")

class OutputTaxonomyAssignmentSchema(TaxonomyAssignmentSchema):
    description: str = Field(..., title="A detailed description of the output (i.e., result) that can be inferred from the subtitles or the visuals. `None` if the taxonomy entry is not included in the tutorial.")
    content_index: list[int] = Field(..., title="Specify the indices of the subtitles or frames that refer/contain/depict the output. Otherwise, provide an empty list.")

class InputTaxonomyAssignmentSchema(TaxonomyAssignmentSchema):
    description: str = Field(..., title="A detailed description of the input (i.e., ingredients/materials, tools) that can be inferred from the subtitles or the visuals. `None` if the taxonomy entry is not included in the tutorial.")
    content_index: list[int] = Field(..., title="Specify the indices of the subtitles or frames that refer/contain/depict the input. Otherwise, provide an empty list.")

class StepTaxonomyAssignmentSchema(TaxonomyAssignmentSchema):
    description: str = Field(..., title="A detailed description of the step that can be inferred from the subtitles or the visuals. Make sure to include all the necessary details such as the tools, materials, ingredients, or the method.")
    content_index: list[int] = Field(..., title="If the step taxonomy entry is included in the tutorial, specify the indices of the subtitles or frames that refer/contain/depict the step.")
